#include "../../src/spectrum/Processor.h"
#include "../../src/spectrum/video/VideoBuffer.h"
#include "ESP32Screen.h"
#include <stdio.h>

#ifdef ESP_PLATFORM
#include "Arduino.h"
#include "esp_timer.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#else
// Mocks for syntax highlighting outside of ESP-IDF
#define vTaskDelay(x)
#define portTICK_PERIOD_MS 1
int64_t esp_timer_get_time() { return 0; }
#endif

// Declare the symbols for the embedded ROM generated by ESP-IDF build system
extern const uint8_t gw03_rom_start[] asm("_binary_gw03_rom_start");
extern const uint8_t gw03_rom_end[] asm("_binary_gw03_rom_end");

extern "C" void app_main(void) {
#ifdef ESP_PLATFORM
  initArduino();
#endif
  printf("Starting ZX Spectrum Emulator on ESP32!\n");

  // Initialize the core Z80 processor
  Processor processor;

  // Load the deeply embedded 48.rom into the emulator's memory space
  size_t romSize = gw03_rom_end - gw03_rom_start;
  printf("Loading embedded ROM... Size: %zu bytes\n", romSize);

  // Debug: Print first 16 bytes of the embedded ROM array
  printf("Embedded ROM first 16 bytes: ");
  for (int i = 0; i < 16 && i < romSize; i++) {
    printf("%02x ", gw03_rom_start[i]);
  }
  printf("\n");

  processor.init(gw03_rom_start, romSize);

  printf("Processor instantiated successfully. ROM loaded and Memory "
         "allocated.\n");

  // Initialize our ESP32 Screen driver
  ESP32Screen screen;
  screen.init(processor.getVideoBuffer());
  screen.setProcessor(&processor);
  processor.setScreen(&screen);

  printf("Screen initialized. Entering main emulation loop...\n");

  // ZX Spectrum runs at ~50Hz (20ms per frame)
  const int frameTimeMicros = 20000;

  int frameCount = 0;
  while (true) {
    int64_t startTime = esp_timer_get_time();

    // Execute 1 frame of T-States (approx 69888 T-States for 48K spectrum)
    processor.executeFrame();

    frameCount++;
    if (frameCount % 50 == 0) {
      if (!processor.isRunning()) {
        printf("Processor stopped due to error: %s\n",
               processor.getLastError().c_str());
      } else {
        printf("Running... PC=%04X, Halted=%d\n",
               processor.getState().registers.PC,
               processor.getState().isHalted());
      }
    }

    // Push the video buffer to the TFT screen
    screen.update();

    int64_t endTime = esp_timer_get_time();
    int64_t elapsedMicros = endTime - startTime;

    // Delay to maintain ~50 FPS and feed the RTOS watchdog
    if (elapsedMicros < frameTimeMicros) {
      int delayMs = (frameTimeMicros - elapsedMicros) / 1000;
      vTaskDelay(delayMs / portTICK_PERIOD_MS);
    } else {
      // Yield briefly even if we are running behind to prevent Watchdog timeout
      vTaskDelay(1);
    }
  }
}
